Set terraform version 11.14 (#215)
* Modified the jenkinsfile so that the docker container is a var and set to 0.11.14 version

* hard coding the image version

* Skipping SES

* Adding default apply commond after plan to ensure the terraform state file is 0.11.14 ready for 0.12 upgrade

* Fixed apply command

* Hardcode plan > apply > 0.12checklist into doterraform function

* change name

* Updating aws provider as instructed. Might be better set as a var.

* Fix:
Error: data.aws_ami.amazon_ami: "owners": required field is not set

* Initial change to enable it to run with:
TERRAGRUNT_VERSION='v0.23.11'
TERRAFORM_VERSION="0.12.24"

this is for the security-groups sub directory code.
Runs with a series of errors and warnings.

* Remove the dependency on the NodeJS in the Docker image.
Set the Docker image to "hmpps-terraform-builder-0-11-14"
Update teh AWS providers to greater than or equal to 2.65

* this file not needed in tf-11

* Reverted tf-12 spike change