This are the changes required to enable this directory of Terraform (security-groups) to plan and apply successfully. This was selected as it has no dependency on external modules thus making a simpler candidate for working through syntax issues etc.
The bastion_vpc_public_cidr from the VPC output (map) no longer required being wrapped in square brackets.

The orginal error this change resolved was:
```
Error: Incorrect attribute value type

  on ssh-bastion-in.tf line 36, in resource "aws_security_group_rule" "ssh_bastion_in":
  36:   cidr_blocks = [values(
  37:     data.terraform_remote_state.vpc.outputs.bastion_vpc_public_cidr,
  38:   )]
    |----------------
    | data.terraform_remote_state.vpc.outputs.bastion_vpc_public_cidr is map of string with 3 elements

Inappropriate value for attribute "cidr_blocks": element 0: string required

```

NOTE: The config code causes approx 88 warnings regarding unused variables which will need to be resolved as in the future this will throw an error.